- name: copy config files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: "/etc/my.cnf.d/"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "./*"
  notify:
    - restart mysql

- name: start mysql
  service:
    name: mysql
    state: started
    enabled: yes
